//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catch_fire_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalArea
    {
        public int GoalAreaId { get; set; }
        public string GoalAreaName { get; set; }
        public byte[] GoalAreaDescription { get; set; }
    }
}
