//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catch_fire_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trait
    {
        public int TraitId { get; set; }
        public string TraitName { get; set; }
        public string TraitDescription { get; set; }
        public Nullable<bool> PositiveTrait { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
